enum Errors {
	MISSING_STATIC_MODEL_GET_IMPLEMENTATION = `MISSING_STATIC_MODEL_GET_IMPLEMENTATION`,
	MISSING_PUBLIC_MODEL_GET_IMPLEMENTATION = `MISSING_PUBLIC_MODEL_GET_IMPLEMENTATION`
}

export class BaseModel {
	static get model(): any {
		throw new Error(Errors.MISSING_STATIC_MODEL_GET_IMPLEMENTATION)
	}
	public get model(): any {
		throw new Error(Errors.MISSING_PUBLIC_MODEL_GET_IMPLEMENTATION)
	}
}